apiVersion: v1
kind: Service
metadata:
  name: was-svc
spec:
  selector:
    app: was
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  selector:
    matchLabels:
      app: was
<<<<<<< HEAD
  replicas: {{.Values.replicaCount}}
=======
  replicas: {{.Values.replicasCount}}
>>>>>>> 666239c65ab05f454005a4b916ad78ba1e1e7ab8
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
<<<<<<< HEAD
        image: {{ .Values.wasImage.repository }}:{{ .Values.wasImage.tag }}
        imagePullPolicy: {{ .Values.wasImage.pullPolicy }}
=======
        image: {{.Values.wasImage.repository}}:{{.Values.wasImage.tag}}
>>>>>>> 666239c65ab05f454005a4b916ad78ba1e1e7ab8
        ports:
        - containerPort: 8080
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-0.mysql-svc.default.svc.cluster.local; do echo waiting for db-0.mysql-svc; sleep 2; done"]
      - name: wait-for-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis-svc.default.svc.cluster.local; do echo waiting for redis-svc; sleep 2; done"]        